---
title: "Šalies ekonominės situacijos poveikis migracijai"
author: "Džiugas Paliulis"
date: '2019-06-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse=TRUE, error=TRUE, warning = FALSE, message= FALSE, cache=TRUE)
```

Viena iš svarbiausių šiuolaikinio pasaulio problemų yra migracija. Kiekvienais metais mažiau išsivysčiūsių šalių gyventojai emigruoja į didesnes ir ekonomiškai stipresnes šalis. Susidaro situacija ur mažose valstybėse gyventojų skaičius pastoviai krenta, o didesnėse, pastoviai auga. Tai dažnai kelia nepasitenkinimą abiejose pusėse. Šalyse, iš kurių buvo emigruota, pradeda stigti darbo jegos ir gyventojų, o šalyse, į kurias imigruojama, gyventojai lieka nepatenkinti, nes immigrantai “vagia” jų darbo vietas ir gali būti paveikta šalies regiono ekonominė struktūra. Todėl pastaraisiais metais daug ekspertų ir ekonomistų svarsto migracijos priežastis ir jų efektą, tyrinėja, kaip ir kodėl ji vyksta, klausia, ar tai gerai šalims, ar blogai. Aš bandysiu žvelgti į tai iš ekonominės pusės, kodėl žmonės emigruoja ir ką tai keičia, kadangi tarp apklaustųjų finansai ir valsybės ekonominė padetis yra dažnai minimos kaip svarbiausios migracijos priežastys.

Pirmiausia yra svarbu pabandyti suprasti, kodėl visgi žmonės emigruoja ir imigruoja. Yra pastebėta, kad migracija yra labiausiai būdinga jaunesniems žmonėms, kurie neturi savų šeimų ir jokių kitų ilgalaikių ryšių ar įsipareigojimų. Taip yra, nes tokie jauni ir nepririšti žmones jaučiasi laisvi rizikuoti ir bandyti pasiekti naujas auštumas, kitaip negu jau vyresni ir sėslūs asmenys. Taip pat yra nustatyta, jog migruojantys žmonės dažniausiai pakliūna į vidutinį gyvenimo lygį savo kilmės šalyse arba šiek tiek aukštesnį nei vidutinį. Tie, kurių gyvenimo lygis vargingesnis, nėra linke emigruoti, nes emigracija gali būti brangus ir gana neužtikrintas procesas. Kelionė į naują šalį, būsto nuoma, laikas darbui ieškotis, tai nėra kažkas ką vargstanti šeima gali sau leisti. Tokiems tikslams bankai irgi retai kada ryžtasi skolinti, o privatūs asmenys  taip pat nėra linke imtis tokios rizikos. Turtingesni žmonės taip pat neturi noro emigruoti, ir labai suprantama: emigrave į kitą šalį,  jie nebutinai galės palaikyti savo buvusį gyvenimo lygi. Jie ir taip gerai gyvena savo kilmės šalyse, todėl jiems tiesiog neverta migruoti, nebent del kažkokių ypatingų priežasčių. Trečia tendencija, kuri buvo pastebėta tarp emigrantų, yra ta, jog jie yra linke migruoti į šalis kurios yra ekonomiškai stipresnės negu jų kilmės šalys, kur jie mato vilties pakeisti savo gyvenimą į geresnę pusę. Tačiau šios visos tendencijos nėra labai konrečios. Laikui bėgant buvo padaryta daug skirtingų apklausų, skirtų migrantams, ir buvo rasta gana daug tiksliau apibrėžtų priežasčių. 

Turbūt svarbiausia iš migracijos priežasčių yra bedarbystė. Pagal Tarptautinės migracijos organizacijos Vilniaus biurą, 2010 metais net 85% žmonių deklaravusių savo išvykimą sakė, kad jie emigruoja, nes negalėjo susirasti jokio norimo dirbti darbo per visus metus ar net ilgiau. Iškeliaudami į kitas šalis jie siekia susirasti tinkamą darbą, ko jie negalėjo padaryti savo kilmės valstybėje. Kita labai dažna priežastis yra didesnio darbo atlyginimo ieškojimas ir / arba aukštesnės karjeros siekimas. Dažnai žmonės nori daugiau užsidirbti, kad galėtų sau daugiau leisti, ir tiek pat dažnai jie to negali padaryti savo darbartinėje aplinkoje nes to neleidžia įmonės kuriose jie dirba bendros valstybės išsivystimo lubos. Todėl jie tikisi, kad iškeliavus kitur jiems pavyks susirasti geresnį darbą, geresnėjė įmonėje, geresnėmis sąlygomis ir užsidirbti daugiau daugiau pinigų, nors ir žino, kad lūkesčiai gali nepasiteninti. Dar viena grupė žmonių yra tie, kurie nori kopti aukštyn karjeros laiptais. Tai labiausiai pastebima tarp jaunesnių ir ambicingesnių asmenų. Mažai ekonomiškai išsivysčiusiose šalys sunku rasti būdą daryti sparčią karjerą. Kaip taisyklė,  po kažkurio laiko karjeristai turi iškeliauti į kitas šalis, kad toliau galėtų tobulinti save. Tik eonomiškai stiprios šalys turi didelį pasirinkimą ir daug progų, ir taip atsiranda ratas, kur visi ambicingi žmonės keliauja į stambesnes šalis ir padeda joms toliau kurti aplinką tinkamą ambicingiems žmonėms, o pasitenine individai lieka ir nieo net nemegina keisti. Kita ne reta migracijos priežastis yra geresnio gyvenimo lygio ieškojimas. Žmonės, pasiekę tam tikrą pragyvenimo lygį, trokšta geresnės infrastrutūros, pasirinkimų ir produktų kokybės,  o tai daug lengviau randama tarp didesnių ir labiau ekonomiškai pažengusių šalių. Yra ir daugiau migracijos priežasčių. Pavyzdžiui, išsilavinimo siekimas, socialinės priežastys, saugos jausmas ir panašiai, tačiau jos nėra tiek daug susijusios su šalių ekonomine situacija, todėl į jas aš nesigilinsiu. Matome, kad migracijos klausimu ekonominės priežastys užima didžiausią dalį, ir yra svarbiausios svarstant, kodėl žmonės migruoja.

Kadangi dabar turime tam tikrą supratimą apie migracijos priežastys, galima pereiti prie klausimo, kokį teigiamą poveikį migracija suteikia šalims. Pradėkime nuo emigracijos. Labiausiai apčiuopiama nauda, kurią suteikia emigracija, yra pinigų persiuntimai atgal į kilmės šalis. Tie pinigai leidžia emigrantų giminėms tureti daugiau pajamų, kurias jie gali skirstyti įvairiems dalykams. Ekspertai norėtų, kad šeimos, gaunančios šias pajamas, jas naudotų investicijoms į valstybę, deja, dažniausiai jos yra sunaudojamos vartojimui – gyvenimo gerinimui. Tačiau tai vistiek padeda toms šeimos gyventi geriau, ar bent išvengti skurdo, ir tai yra sveikintinas poveikis. Kitas teigiamas  emigracijos efektas, kuris dažnai ginčijamas, yra nedarbo kritimas. Pagal vieną teorijų, žmonės nerandantys tinkamo darbo savo kilmės šalyje turėtų emigruoti į kitas, kur jis yra reikalingas, o kitų šalių žmonės, kurių profesija yra reikalinga tai šaliai, turėtų imigruoti į ją. Pagal šią teoriją darbo lygis turėtų tapti mažas visose šalyse, ir darbo jėga  būtų lygiai pasiskirsčiusi. Tačiau realybėje to dažnai nematome, todėl ir kyla ginčų, ar ši teorija teisinga. Mano nuomone – taip, ji teisinga, ir tai yra migracijos pozytivus elementas, tiesiog dažnai žmogiškoji veikla iškraipo šį procesą.  Asmenys, kurie kritikuoja šią teoriją, maišo ją su kitais migracijos efektais. 
Kalbant apie imigracijos teigiamus poveikius, svarbiausia yra darbo jėgos atkeliavimas į šalį, ypač specialistų, kurių trūksta tai šaliai. Kai kurie sektoriai visada turi daugiau darbo jėgos negu kiti, ir vienintelis spartus būdas gauti darbo jėgos, neįskaitant patiems užsiugdyti, yra imigracija. Kiekvieno specialisto parengimas kainuoja, be to, daugelis profesijų yra nepopuliarios, todėl net didžiausiose šalyse yra tokių darbo jėgos vietų, kurias yra sunku užpildyti, ir būtent imigracija padeda su tuo susitvarkyti. Taip pat imigrantai su savimi atsiveža savo santaupas ir potencialą pradėti savo verslus – investuoti į šalį. Atkeliavę žmonės gyventi tampa tos šalies vartotojais, ir po kažkiek laiko mokesčių mokėtojais, taigi jie prisiriša prie jos. Tai reiškia, kad jie gali pradėti galvoti apie ilgalaikį investavimą ir net savo asmeninį verslą, jei tik jie jaučiasi ekonomiškai saugūs. Migracija turi nemažai teigiamų efektų ir teoriškai turėtų būti svarbus įrankis vystytis šalims.

Dabar mes pereisime prie migracijos neigiamo poveikio. Pradėkime nuo emigracijos. Pirmas efektas, ir turbūt svarbiausias yra darbo jėgos praradimas, ir ypač aukštos kvalifikacijos darbo jėgos Tai vadinama protų nutekėjimu. Šis efektas yra dažnai naudojamas kaip argumentas prieš ankščiau minėtą  darbo jėgos išsilyginimo teoriją, tačiau iš tiesų šie du efektai egzistuoja atskirai, ir yra rimta problema. Tai dažniausiai atsitinka dėl žmonių noro gauti geresnį atlyginimą ir  siekti aukštesnio pragyvenimo lygio, o tai  reiškia, kad nors darbo vietų šalyje toms specialybėms yra, patys asmenys nėra patenkinti sąlygomis ir emigruoja. Per ilgesnį laiką  tai  stipriai paveikia valstybės vystymąsi,  ypač  dėl to, kad dažnai išvyksta norintys ir mokantys dirbti, o  pasilieka nedarbingi asmenys. Dar vienas emigracijos poveikis yra tas, jog dažniausiai emigruoja jauni žmonės. Tai reiškia, kad šalies populiacija sensta, ir darbingumas mažėja, tai paveikia ateities kartų mąstymą ir ūgdymą. Trečias poveikis yra labiau socialinis: žmonės pradeda jaustis mažiau saugūs, investuotojai abejoja šalies perspektyvomis ir renkasi į jas neinvestuoti, ir taip prasideda stagnacijos ciklas. Paskutinis svarbus poveikis yra tai, kad emigrantai dažnai bando apgauti valstybes, neskelbia savo emigracijos ir naudaojasi visokiomis privilegijomis, kas taip pat veikia šalis ir jų požiūrį į migraciją.
Imigracija taip pat turi neigiamų poveikių. Pagrindinis iš jų yra šalies gyventojų išstūmimas iš darbo rinkos. Neretai imigrantai yra pasiryžę dirbti už daug mažesnį atlyginimą negu kiti, ir todėl juos verslininkams labiau apsimoka įdarbinti. Tai kelia ne tik žmonių nepasitenkinimą, bet ir bedarbystę. Darbo rinka pradeda svyruoti, o mažesnės bendruomenės gali visai suirti. Kartu su žmonėmis atkeliauja ir jų poreikių tenkinimas ir socialinės paramos, kas krenta ant piliečių pečių. Taip pat iškyla ir socialinių bei sugumo klausimų. Žmonės vengia arba yra linkę sunkiai priimti naujus asmenis,  – kiti kelia jiems baimę ir nejaukumą. Yra pastebėta, kad su migracija kyla ir nuikaltimų saičius. Matome, kad migracija gali sukelti beveik tiek pat neigiamos įtakos, kiek ir teigiamos. Tai reiškia, kad ji nėra vienapusiškas ar vienareikšmis procesas.

Apibendrinant migracijos pagrindines ir svarbiausias priežastis jas tiktų vadinti ekonominėmis. Nuo darbo vietų trūkumo iki didesnių atlyginimų, geresnių gyvenimo sąlygų, karjieros perspektyvų. Tačiau tai yra paradoksalus procesas. Migracijos teigiamas poveikis yra darbo jėgos pasiskirstymas, tačiau neigiamas poveikis yra protų nutekėjimas ir gyventojų išstūmimas iš darbo vietų dėl imigrantų atvykimo. Emigrantai parsiunčia pinigų į savo kilmės šalį, bet taip pat išsiveža savo santaupas iš gimtinės... Mano nuomone, šalies ekonominė situacija ir migracija yra glaudžiai susijusios, jos gali kelti ir ekonomikos augimą, ir jos stagnaciją. Migracija yra abipusis reiškinys, ir žmonės turėtų galvoti ne apie tai, ar migracija yra geras ar blogas reiškinys, o apie tai, kaip padidinti migracijos pozityvius efektus ir išvengti negatyvių.


